# Generated by Django 5.1.6 on 2025-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('national_code', models.CharField(max_length=10, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('birth_date', models.DateField()),
                ('address', models.TextField(max_length=300)),
                ('slug', models.SlugField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('province', models.CharField(choices=[('021', 'تهران'), ('061', 'خوزستان'), ('077', 'بوشهر'), ('031', 'اصفهان'), ('051', 'خراسان رضوی'), ('071', 'فارس'), ('041', 'آذربایجان شرقی'), ('011', 'مازندران'), ('034', 'کرمان'), ('026', 'البرز'), ('013', 'گیلان'), ('074', 'کهگیلویه و بویراحمد'), ('044', 'آذربایجان غربی'), ('076', 'هرمزگان'), ('086', 'مرکزی'), ('035', 'یزد'), ('000', 'فرامنطقه\u200cای'), ('083', 'کرمانشاه'), ('028', 'قزوین'), ('054', 'سیستان و بلوچستان'), ('081', 'همدان'), ('084', 'ایلام'), ('017', 'گلستان'), ('066', 'لرستان'), ('024', 'زنجان'), ('045', 'اردبیل'), ('025', 'قم'), ('087', 'کردستان'), ('023', 'سمنان'), ('038', 'چهارمحال و بختیاری'), ('058', 'خراسان شمالی'), ('056', 'خراسان جنوبی')], default=None, max_length=3)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='ssoweb_pers_created_77f4b4_idx')],
            },
        ),
    ]
