# Generated by Django 5.1.6 on 2025-03-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssoweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('R', 'حقیقی'), ('L', 'حقوقی')], max_length=1, null=True),
        ),
    ]
